// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSOI68iUYV1YTVzytj4Z5rIyybEN1WqWM',
    appId: '1:462996182279:web:93c3cd534bb727cce421a2',
    messagingSenderId: '462996182279',
    projectId: 'e2ee-room',
    authDomain: 'e2ee-room.firebaseapp.com',
    storageBucket: 'e2ee-room.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8O6LkDMPlOm5luxj7ZuI-DntfrwQC1CU',
    appId: '1:462996182279:android:9e442c43286a5bc8e421a2',
    messagingSenderId: '462996182279',
    projectId: 'e2ee-room',
    storageBucket: 'e2ee-room.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-FCefx072SaFmhmnHylHbTor5ZaTrpT0',
    appId: '1:462996182279:ios:d416204068da0604e421a2',
    messagingSenderId: '462996182279',
    projectId: 'e2ee-room',
    storageBucket: 'e2ee-room.appspot.com',
    iosClientId: '462996182279-n9qk95saghe8jl4eil9r2lng8n2ss7ba.apps.googleusercontent.com',
    iosBundleId: 'com.example.privateRoom',
  );
}
